= Release Notes Guide and Template
Sarah White
:toc2:
:icons:
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlight.js

[Warning]
====
* Need to confirm that template is adequately covered by the MIT license or if a CC license should also be applied.
* Need links to examples once the release notes for 0.1.4 are completed.
* Need an upgrade guide.
* Need to choose between New and Noteworthy or Highlights or What's New
* Need to choose between Additional Features and Changes or Minor Features and Changes or Other Features and Changes
====

This guide provides an outline, writing style guidelines and a document template to help you structure and write your release notes.
It is not a set of rules.
After you fork this document or copy the example template found below, feel free to remove or modify sections and syntax that aren't applicable to the release.

== Release Notes Audience

Asciidoctor users and developers

== Writing and style guidelines

*Header*

Include and display:

* title with release version number
* version release date
* table of contents

*Preamble*

In a few paragraphs, introduce the enhancements and changes that provide the most influential benefits or affect the majority of the user base.
Then, in general terms, explain the benefit each enhancement/change has for the users.
This is not where you describe technical specifics (code examples).

Think overall themes, for example:

* This release is for all the users who have been waiting for a DocBook 5 backend.
* We've sped up the processor by three minutes!
* Asciidoctor now interfaces with all your applicances.

*Installation and Upgrade Notes*

This section should be brief and link to other documents for users requiring more information.
If there are no release-specific installation or upgrade changes, simply provide the links to the general installation and upgrade guides.

Include information about:

* user or developer environment changes
* installation/compilation method changes
* links to installation guide, upgrade guide, and sourcecode repository

*New and Noteworthy/Highlights/What's New*

This section is for specifically describing and providing code snippets for each enhancement or change that makes this release significant.

*Features/Changes*

Describe what this new enhancement or change does (its purpose/goal) and how it works.
If it provides numerous features and/or results, they can be listed.

When applicable, include:

* attribute, option, syntax, etc. names and how/when they operate
* example code
* tips or caveats

Also, provide links to related documentation or more information.

*Additional Features and Changes/Minor Features and Changes/Other Features and Changes*

Minor features and changes can be listed.
Each list item includes a one sentence description with link to further documentation/information if applicable.

*Changelog*

The Changelog is an autogenerated, bulleted list that is included from a separate source file.
Each list item states the issue number, linked to the issue tracker, and a one sentence description of the issue.

*Deprecations*

This section is structured the same way as the New and Noteworthy section.

*Potential Breaking Changes*

This section is structured the same way as the New and Noteworthy section.

*Known Problems*

This section is structured the same way as the Changelog section.

== Template

Copy the template below (between the set of dashes (+----+)) and paste it into a new document.
 
.Release Notes Template
[source,asciidoc]
----
= Asciidoctor x.x.x Release Notes
Author Name
_Release Date_
:toc2:
:source-highlighter:
:icons:
:sectanchors:
// Additional front matter, attributes, and references

////
 * Based on the Release Notes Template
 * Copyright (c) 2013 Sarah White and the Asciidoctor Project
 * Licensed under the MIT License
 * http://github.com/asciidoctor/asciidoctor/blob/master/LICENSE
 * Version 0.1.0.RC1
 *
 * http://www.github.com/asciidoctor/asciidoctor-documentation
////

// Insert introduction paragraphs here

== Installation and Upgrade Notes

== New and Noteworthy/Highlights/What's New

=== Feature 1 title

=== Feature 2 title

=== Feature 3 title

=== Feature X title

== Additional Features and Changes/Minor Features and Changes/Other Features and Changes

* minor change
* minor change
* minor change

== Changelog

xxx issues were fixed in Asciidoctor x.x.x.
 
* {URL Ref}[Issue-#] Issue title or 1 sentence description

== Deprecations

=== Deprecated feature 1 title

=== Deprecated feature X title

== Potential Breaking Changes

=== Breaking change 1 title

=== Breaking change X title

== Contributors

This Asciidoctor release would not have been possible without contributions from the following people:

* Contributor Name
** Contribution 1
** Contribution 2
* Contributor Name
** Contribution

== Known Problems

These issues, discovered after its release, affect Asciidoctor x.x.x.

* {URL Ref}[Issue-#] Issue title or 1 sentence description

== Feedback and Help

The Asciidoctor Project is developed to help you sucessfully write and publish your content.
But we can't do that without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the mailing list or IRC.

If you discover errors or ommisions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix. 
The Code and Content Contributor Manual provides detailed information on how to create, style, and submit issues, feature requests, code, and documentation to the Asciidoctor Project. 
New contributors are always welcome!
----

== Credits

This guide was influenced by the release notes published for {http://www.gradle.org/docs/current/release-notes}[Gradle], {http://www.gimp.org/release-notes/gimp-2.6.html}[Gimp], {http://guides.rubyonrails.org/2_3_release_notes.html}[Ruby on Rails], {https://cwiki.apache.org/confluence/display/OOOUSERS/AOO+4.0+Release+Notes}[Apache OpenOffice], and {http://developer.android.com/sdk/RELEASENOTES.html}[Android SDK].
